margin = 92
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
import_to_using = true
pipe_to_function_call = false
short_to_long_function_def = true
long_to_short_function_def = true
always_use_return = false
whitespace_in_kwargs = false
annotate_untyped_fields_with_any = true
conditional_to_if = true
normalize_line_endings = "unix"
trailing_comma = true
trailing_zero = true
join_lines_based_on_source = true
indent_submodule = true
separate_kwargs_with_semicolon = true
surround_whereop_typeparameters = true
short_circuit_to_if = false
disallow_single_arg_nesting = true
